; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; PlatformIO Project Configuration File

[env]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps =
  knolleary/PubSubClient@^2.8.0
  olikraus/U8g2@^2.35.19
  https://github.com/ShaggyDog18/SD_ZH03B
  br3ttb/PID@^1.2.1
  tzapu/WiFiManager@^2.0.16-rc.2

[env:esp32_usb]
upload_protocol = esptool
upload_port = /dev/ttyUSB0  
upload_speed = 921600       


[env:esp32_ota]
upload_protocol = espota
upload_port = 192.168.1.99    
upload_flags =

